"""Add action_url and notification_type to Notification

Revision ID: 955cf684a194
Revises: c7d8e9f0a1b2
Create Date: 2026-06-20 22:19:37.712743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955cf684a194'
down_revision: Union[str, Sequence[str], None] = 'c7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'ai_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('applications', 'report_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('action_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'action_url')
    op.drop_column('notifications', 'notification_type')
    op.alter_column('applications', 'report_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('applications', 'ai_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
